ci: Improve package release on tagging 2
[why]
We want to deploy on Darwin also only for master related pipelines.

[how]
As the setup with the rules and an additional script part is quite
complex we pull it out as job template and use it for both Ubuntu and
Darwin.

Signed-off-by: Fini Jastrow <ulf.fini.jastrow@desy.de>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -133,13 +133,16 @@ Darwin test:
 
 Darwin install:
         stage: deploy
-        extends: .setup_darwin
+        extends:
+                - .setup_darwin
+                - .deploy_generic
         needs:
                 - job: Darwin test
                   artifacts: false
                 - job: Darwin build
                   artifacts: true
         script:
+                - eval $DEPLOY_ALLOWED || exit 0
                 - export PATH=/usr/local/bin:${PATH}
                 - DESTDIR=${CI_PROJECT_DIR}/macos_install ninja -C macos-build install
         artifacts:
@@ -203,18 +206,9 @@ Windows test:
 
 # Template to put debian packages in the gitlab package repo
 .deploy_debian:
-        rules:
-                - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Never when creating a MR
-                  when: never
-                - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH # Merge request merged (or direct push)
-                - if: $CI_COMMIT_TAG =~ /^DOOCSVERSION_[0-9]+_[0-9]+_[0-9]+$/ # Some tag pushed that is DOOCSVERSION_23_13_5 or equivalent
+        extends: .deploy_generic
         script:
-                - if [ -n "$CI_COMMIT_TAG"  -a "$CI_COMMIT_REF_NAME" != "$CI_DEFAULT_BRANCH" ]; then
-                        echo "Searching for ${CI_COMMIT_SHA} in ${CI_DEFAULT_BRANCH} branch";
-                        export COMMIT_ON_MASTER=`git log --pretty=oneline --decorate=short origin/${CI_DEFAULT_BRANCH} | grep -c "^${CI_COMMIT_SHA} "`;
-                        if [ "$COMMIT_ON_MASTER" -lt 1 ]; then echo "Tag pipeline not for ${CI_DEFAULT_BRANCH} branch - abort job"; exit 0; fi;
-                        echo "Success, continuing deploy job for tag commit...";
-                  fi
+                - eval $DEPLOY_ALLOWED || exit 0
                 - (export http_proxy="http://xfelproxy:3128/"; export https_proxy="http://xfelproxy:3128/";
                     DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends build-essential debhelper devscripts curl)
                 - (cd build.release; debuild -i -us -uc -b)
@@ -284,3 +278,25 @@ Windows test:
 .setup_windows:
         tags:
                 - windows10
+
+# Template to allow deployment only on master branch related push/tag
+# Note: Apart from the rules this templates adds, one needs to eval the
+# variable in the actual job like
+#    eval $DEPLOY_ALLOWED || exit 0
+# We need this because yaml merging does not provide a way to combine
+# multiple script arrays
+.deploy_generic:
+        rules:
+                - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Never when creating a MR
+                  when: never
+                - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH # Merge request merged (or direct push)
+                - if: $CI_COMMIT_TAG =~ /^DOOCSVERSION_[0-9]+_[0-9]+_[0-9]+$/ # Some tag pushed that is DOOCSVERSION_23_13_5 or equivalent
+
+        variables:
+                DEPLOY_ALLOWED: >
+                                if [ -n '$CI_COMMIT_TAG'  -a '$CI_COMMIT_REF_NAME' != '$CI_DEFAULT_BRANCH' ]; then
+                                      echo '===> Searching for ${CI_COMMIT_SHA} in ${CI_DEFAULT_BRANCH} branch:';
+                                      export COMMIT_ON_MASTER=`git log --pretty=oneline --decorate=short origin/${CI_DEFAULT_BRANCH} | grep -c "^${CI_COMMIT_SHA} "`;
+                                      if [ "$$COMMIT_ON_MASTER" -lt 1 ]; then echo '===> Tag pipeline not for ${CI_DEFAULT_BRANCH} branch - abort job'; false;
+                                      else echo '===> Success, continuing deploy job for tag commit...'; fi;
+                                fi
