changelogger: Fail early on wrong tag regex
[why]
When the tag prefix (which is a regex) does not match any existing tag
the script ends with a strange error message:
  fatal: ..: '..' is outside repository

[how]
Check that at least one tag matches the prefix/regex.

Signed-off-by: Fini Jastrow <ulf.fini.jastrow@desy.de>

diff --git a/tools/changelogger b/tools/changelogger
--- a/tools/changelogger
+++ b/tools/changelogger
@@ -3,7 +3,7 @@
 # Autogenerate the debian/changelog from git tags
 # The output can be further configured by meson, or use -N
 #
-# This is version 2.0 "Binturong", changed 11 Feb 2021
+# This is version 2.1 "Binturong", changed 14 Feb 2021
 #
 # A git version tag have the form 'name_M_m_p' where M, m and p are
 # positive integers with the semantic version number. If no p is given
@@ -70,6 +70,10 @@ allcommits=`git ${workdir} log --format="ref='%H' email='%an <%ae>' dat='%cD'"`
 head=`printf "${allcommits}" | head -n 1`
 root=`printf "${allcommits}" | tail -n 1`
 tags=`git ${workdir} for-each-ref --shell --sort=-v:refname --format=ref="%(refname) tagger=%(taggername) email=%(creator) dat=%(creatordate:rfc)" "refs/tags/${tag_pre}" --merged`
+if [ -z "${tags}" ]; then
+	echo >&2 "`basename "$0"`: Error: Can not find any tag matching '${tag_pre}' (maybe add a star ('*')?)"
+	exit 2
+fi
 
 # find out if HEAD is a tagged commit
 top_tag=`git ${workdir} for-each-ref --sort=-v:refname --count=1 --format='%(refname)' "refs/tags/${tag_pre}" --merged`
